version: "3"
services:

  db:
    container_name: kotiolut-db
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: kotiolut-wiki
      POSTGRES_PASSWORD: kotiolut-secret
      POSTGRES_USER: kotiolut-admin
    logging:
      driver: "none"
    env_file:
      - ../.env
    restart: unless-stopped
    volumes:
      - "./db-data:/var/lib/postgresql/data"
      - "../backup:/tmp/backup"

  wiki:
    container_name: kotiolut-wiki
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: kotiolut-admin
      DB_PASS: kotiolut-secret
      DB_NAME: kotiolut-wiki
    env_file:
      - ../.env
    restart: unless-stopped
    ports:
      - "8080:3000"
